# Generated by Django 5.0.3 on 2024-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
            ],
            options={
                'db_table': 'flats',
                'default_permissions': (),
            },
        ),
    ]
